### ISSUE TITLE
Bunch of corrections

### ISSUE THREAD

**Issue by szopeno** [google/mystyle#7]
mv ../shape_predictor_68_face_landmarks.dat.bz2 ../ffhq.pkl ../model_ir_se50.pth ../faces_w_encoder.pt checkpoints/
# FIRST correction required to work
mv data_preprcoess/ data_preprocess # (!!)
# SETTING PYTHONPATH required to work
export PYTHONPATH=$PYTHONPATH:`pwd`

# this fails, dlib model is in bz2 archive, must be bunzipped
python data_preprocess/0_align_face.py \
    --images_dir test_album \
    --save_dir test \
    --trash_dir trash \
    --landmarks_model checkpoints/shape_predictor_68_face_landmarks.dat.bz2 \
    --id_model checkpoints/model_ir_se50.pth

Traceback (most recent call last):
  File "PATH-EDITED/mystyle/data_preprocess/0_align_face.py", line 242, in <module>
    main()
  File "PATH-EDITED/mystyle/data_preprocess/0_align_face.py", line 219, in main
    lnds_predictor = dlib.shape_predictor(str(args.landmarks_model))
RuntimeError: Unexpected version found while deserializing dlib::shape_predictor.

cd checkpoints
bunzip2 shape_predictor_68_face_landmarks.dat.bz2 # (!)
cd ..
python data_preprocess/0_align_face.py \
    --images_dir test_album \
    --save_dir test \
    --trash_dir trash \
    --landmarks_model checkpoints/shape_predictor_68_face_landmarks.dat \
    --id_model checkpoints/model_ir_se50.pth

OK - now it fails a bit further, but it's because I have n physical GPU no board. I managed to run arcnet/resnet withut GPU before, so I will try later to check whether I'll be able to do it here. We'll see.

**Comment by szopeno** [comment]
Corrected it to work with CPU only. Damn it's slow without GPU :-) I have a question: 

what should be the input image resolution for superresolution? It seems that images have to be 1024x1024; With images with smaller resolution, I am getting errors like this (path edited)

Traceback (most recent call last):
  File "project.py", line 120, in <module>
    main()
  File "project.py", line 116, in main
    project(args)
  File "project.py", line 60, in project
    sample = alpha_projector.reconstruct(sample)
  File "mystyle/reconstruct/base_projector.py", line 66, in reconstruct
    recon_loss = self.reconstruction_loss(synth, target, mask=sample.mask)
  File "mystyle/reconstruct/base_projector.py", line 52, in reconstruction_loss
    return super(BaseProjector, self).reconstruction_loss(degraded_synth, target)
  File "mystyle/reconstruct/base_reconstructor.py", line 50, in reconstruction_loss
    dist = self.lpips(synth, target)
  File "HOME.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "HOME/.local/lib/python3.6/site-packages/lpips/lpips.py", line 124, in forward
    diffs[kk] = (feats0[kk]-feats1[kk])**2  = (feats0[kk]-feats1[kk])**2
RuntimeError: The size of tensor a (255) must match the size of tensor b (127) at non-singleton dimension 3

**Comment by luchaoqi** [comment]
> Corrected it to work with CPU only. Damn it's slow without GPU :-) I have a question:
> 
> what should be the input image resolution for superresolution? It seems that images have to be 1024x1024; With images with smaller resolution, I am getting errors like this (path edited)
> 
> Traceback (most recent call last): File "project.py", line 120, in main() File "project.py", line 116, in main project(args) File "project.py", line 60, in project sample = alpha_projector.reconstruct(sample) File "mystyle/reconstruct/base_projector.py", line 66, in reconstruct recon_loss = self.reconstruction_loss(synth, target, mask=sample.mask) File "mystyle/reconstruct/base_projector.py", line 52, in reconstruction_loss return super(BaseProjector, self).reconstruction_loss(degraded_synth, target) File "mystyle/reconstruct/base_reconstructor.py", line 50, in reconstruction_loss dist = self.lpips(synth, target) File "HOME.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "HOME/.local/lib/python3.6/site-packages/lpips/lpips.py", line 124, in forward diffs[kk] = (feats0[kk]-feats1[kk])**2 = (feats0[kk]-feats1[kk])**2 RuntimeError: The size of tensor a (255) must match the size of tensor b (127) at non-singleton dimension 3

Same here, not sure if there are any requirements about image resolution
